import Foundation
import AppKit

/// Raw payload read from the pasteboard before classification.
struct CapturedContent {
    var text: String?
    var imageData: Data?
    var declaredURL: String?
    var sourceApp: String?
    var sourceAppBundleID: String?
}

/// Polls `NSPasteboard` on the main thread and emits new content.
/// SPEC: must run on the main thread; default interval 0.5s.
@MainActor
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Invoked with new clipboard content whenever a change is detected.
    var onCapture: ((CapturedContent) -> Void)?

    /// When true, pasteboard items marked with privacy UTIs (password manager
    /// content, transient or auto-generated content) are skipped entirely and
    /// never read or persisted. Defaults to true.
    var ignorePrivacyTypes = true

    /// Bundle identifiers whose clipboard copies should never be captured.
    /// Kept in sync from settings by `AppState`.
    var ignoredBundleIDs: [String] = []

    /// When true, the timer keeps running but all pasteboard reading is skipped.
    /// Use `pause()` / `resume()` to toggle.
    private(set) var isPaused = false

    /// Pasteboard types that signal sensitive / non-persistable content.
    /// See http://nspasteboard.org for the de-facto standard used by 1Password,
    /// Bitwarden and other password managers.
    private static let privacyTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    private(set) var isRunning = false

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start(interval: TimeInterval) {
        stop()
        lastChangeCount = pasteboard.changeCount
        let safeInterval = max(0.1, interval)
        let timer = Timer.scheduledTimer(withTimeInterval: safeInterval, repeats: true) { [weak self] _ in
            // Timer fires on the main run loop; hop to the main actor explicitly.
            Task { @MainActor in
                self?.poll()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
        isRunning = true
        AppLogger.clipboard.info("Monitor started (interval \(safeInterval)s)")
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
    }

    func restart(interval: TimeInterval) {
        start(interval: interval)
    }

    /// Suspends clipboard capture without tearing down the timer. The pasteboard
    /// change count is realigned on resume so copies made while paused are not
    /// retroactively captured.
    func pause() {
        guard !isPaused else { return }
        isPaused = true
        AppLogger.clipboard.info("Monitor paused")
    }

    func resume() {
        guard isPaused else { return }
        isPaused = false
        // Ignore anything copied while we were paused.
        lastChangeCount = pasteboard.changeCount
        AppLogger.clipboard.info("Monitor resumed")
    }

    /// Marks the current pasteboard state as already handled. Call this right
    /// after writing to the pasteboard ourselves to avoid re-capturing it.
    func acknowledgeCurrentChange() {
        lastChangeCount = pasteboard.changeCount
    }

    private func poll() {
        // While paused, swallow changes (and keep the change count current) so
        // nothing is captured and resuming doesn't replay buffered copies.
        guard !isPaused else {
            lastChangeCount = pasteboard.changeCount
            return
        }
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        guard let content = readContent() else { return }

        // App ignore list: skip copies originating from ignored apps.
        if let bundleID = content.sourceAppBundleID, ignoredBundleIDs.contains(bundleID) {
            AppLogger.clipboard.info("Skipped clipboard item from ignored app \(bundleID, privacy: .public)")
            return
        }

        onCapture?(content)
    }

    /// Reads the current pasteboard, preferring text over images when both
    /// are present (rich content), and falling back to images / URLs.
    func readContent() -> CapturedContent? {
        // Privacy guard: never read or persist content that password managers
        // and the system mark as concealed / transient / auto-generated.
        if ignorePrivacyTypes {
            let types = pasteboard.types ?? []
            if !Set(types).isDisjoint(with: Self.privacyTypes) {
                AppLogger.clipboard.info("Skipped pasteboard item marked with a privacy type")
                return nil
            }
        }

        let frontApp = NSWorkspace.shared.frontmostApplication
        let sourceApp = frontApp?.localizedName
        let sourceAppBundleID = frontApp?.bundleIdentifier

        let string = pasteboard.string(forType: .string)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let declaredURL = pasteboard.string(forType: .URL)

        if let string, !string.isEmpty {
            return CapturedContent(
                text: string,
                imageData: nil,
                declaredURL: declaredURL,
                sourceApp: sourceApp,
                sourceAppBundleID: sourceAppBundleID
            )
        }

        if let imageData = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
            return CapturedContent(
                text: nil,
                imageData: imageData,
                declaredURL: nil,
                sourceApp: sourceApp,
                sourceAppBundleID: sourceAppBundleID
            )
        }

        if let declaredURL, !declaredURL.isEmpty {
            return CapturedContent(
                text: declaredURL,
                imageData: nil,
                declaredURL: declaredURL,
                sourceApp: sourceApp,
                sourceAppBundleID: sourceAppBundleID
            )
        }

        return nil
    }
}
